queue_rules:
  - name: default
    queue_conditions:
      - base = main
      - check-success = @github-actions/result
    merge_conditions:
      - check-success = @github-actions/result
    merge_method: squash

pull_request_rules:
  - name: automatically queue approved PRs
    conditions:
      - base = main
      - '#approved-reviews-by >= 1'
    actions:
      queue:
        name: default
